import type { Metadata } from "next";
import "./globals.css";
import MyContainer from "@/components/Shared/MyContainer";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <MyContainer> {children}</MyContainer>
      </body>
    </html>
  );
}
